version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
        - ./server/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - ${POSTGRES_PORT}:5432

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  api:
    init: true
    image: ima_api
    build: ./server
    restart: always
    volumes:
        - ./server:/app:cached
    ports:
        - '${PORT}:${PORT}'


