const users = require('./users/users.service.js');
const userPreferences = require('./user_preferences/user_preferences.service.js');
const userType = require('./user_type/user_type.service.js');
const imageUrl = require('./image_url/image_url.service.js');
const joinUsersAndUserPreferences = require('./join__users_and_user_preferences/join__users_and_user_preferences.service.js');
const joinUsersAndUserType = require('./join__users_and_user_type/join__users_and_user_type.service.js');
const joinArticleAndUser = require('./join_article_and_user/join_article_and_user.service.js');
const joinArticleAndImage = require('./join_article_and_image/join_article_and_image.service.js');
const joinArticleAndTag = require('./join_article_and_tag/join_article_and_tag.service.js');
const tag = require('./tag/tag.service.js');
const article = require('./article/article.service.js');
const relatedArticle = require('./related_article/related_article.service.js');
const joinTagAndImage = require('./join_tag_and_image/join_tag_and_image.service.js');
const sitePreferences = require('./site_preferences/site_preferences.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(userPreferences);
  app.configure(userType);
  app.configure(imageUrl);
  app.configure(joinUsersAndUserPreferences);
  app.configure(joinUsersAndUserType);
  app.configure(joinArticleAndUser);
  app.configure(joinArticleAndImage);
  app.configure(joinArticleAndTag);
  app.configure(tag);
  app.configure(article);
  app.configure(relatedArticle);
  app.configure(joinTagAndImage);
  app.configure(sitePreferences);
};
